"""
Code "generated by the LLM" from the natural-language specifications in
prompts.txt (Prompts 1 and 2). In this submission the LLM is Claude,
used directly in a coding session rather than a locally-hosted
Qwen2.5-Coder model (the reference notebook's own setup cell notes it
isn't using the local model either) - the engineering pipeline being
practised (specify -> generate -> inspect -> approve -> execute ->
validate) is the same either way.

Per the notebook's "do not blindly execute generated code" step, this
file is clearly separated from trusted_model.py (the independently
written oracle) so the two can be compared.
"""

from pgmpy.models import DiscreteBayesianNetwork
from pgmpy.factors.discrete import TabularCPD
from pgmpy.parameter_estimator import DiscreteMLE, DiscreteBayesianEstimator


def build_network_from_prompt1():
    """
    Prompt 1 asked: "Build a pgmpy DiscreteBayesianNetwork for the
    network C -> R, C -> S, R -> W, S -> W with the given CPTs, call
    check_model(), and return the model."
    """
    model = DiscreteBayesianNetwork([("C", "R"), ("C", "S"), ("R", "W"), ("S", "W")])
    model.add_cpds(
        TabularCPD("C", 2, [[0.5], [0.5]]),
        TabularCPD("R", 2, [[0.8, 0.2], [0.2, 0.8]], evidence=["C"], evidence_card=[2]),
        TabularCPD("S", 2, [[0.5, 0.9], [0.5, 0.1]], evidence=["C"], evidence_card=[2]),
        TabularCPD(
            "W", 2,
            [[0.99, 0.10, 0.10, 0.01], [0.01, 0.90, 0.90, 0.99]],
            evidence=["R", "S"], evidence_card=[2, 2],
        ),
    )
    assert model.check_model()
    return model


def fit_mle(data, graph_edges):
    """
    Prompt 2 asked: "Given a pandas DataFrame `data` with columns
    C,R,S,W and the fixed graph structure, fit the CPTs by maximum
    likelihood using pgmpy's MaximumLikelihoodEstimator and return a
    fitted DiscreteBayesianNetwork. Do not relearn the graph structure."
    """
    model = DiscreteBayesianNetwork(graph_edges)
    model.fit(data, estimator=DiscreteMLE())
    return model


def fit_bayesian(data, graph_edges, prior_type="BDeu", equivalent_sample_size=10):
    """
    Prompt 3 (revision of Prompt 2) asked: "Change the estimator to
    BayesianEstimator with an explicit Dirichlet-equivalent prior
    (BDeu, equivalent_sample_size parameter), keeping the graph fixed."
    """
    model = DiscreteBayesianNetwork(graph_edges)
    estimator = DiscreteBayesianEstimator(
        prior_type=prior_type, equivalent_sample_size=equivalent_sample_size,
    )
    model.fit(data, estimator=estimator)
    return model


# --- A deliberately broken CPT (columns don't sum to 1) -------------------
def build_broken_cpt_model():
    """Intentionally invalid: the W|R,S columns sum to 1.05, not 1.0."""
    model = DiscreteBayesianNetwork([("C", "R"), ("C", "S"), ("R", "W"), ("S", "W")])
    model.add_cpds(
        TabularCPD("C", 2, [[0.5], [0.5]]),
        TabularCPD("R", 2, [[0.8, 0.2], [0.2, 0.8]], evidence=["C"], evidence_card=[2]),
        TabularCPD("S", 2, [[0.5, 0.9], [0.5, 0.1]], evidence=["C"], evidence_card=[2]),
        TabularCPD(
            "W", 2,
            [[0.99, 0.10, 0.10, 0.01], [0.06, 0.90, 0.90, 0.99]],  # bug: 0.06 instead of 0.01
            evidence=["R", "S"], evidence_card=[2, 2],
        ),
    )
    return model


# --- A subtler failure: correct numbers, wrong evidence-column order ------
def build_reversed_evidence_order_model():
    """
    Still normalizes to 1 per column (check_model() will accept it), but
    the two columns of CPD(R | C) are swapped - as if the generated code
    assumed the evidence state order was (C=1, C=0) instead of (C=0, C=1).
    Every individual number is still a valid probability (each column
    still sums to 1), so `check_model()` happily accepts it; the model
    nonetheless represents P(R | C=1)=0.2, P(R | C=0)=0.8 - the exact
    reverse of the specification - which only a semantic test can catch.
    """
    model = DiscreteBayesianNetwork([("C", "R"), ("C", "S"), ("R", "W"), ("S", "W")])
    model.add_cpds(
        TabularCPD("C", 2, [[0.5], [0.5]]),
        # BUG: columns swapped relative to evidence_card's implied (C=0, C=1) order
        TabularCPD("R", 2, [[0.2, 0.8], [0.8, 0.2]], evidence=["C"], evidence_card=[2]),
        TabularCPD("S", 2, [[0.5, 0.9], [0.5, 0.1]], evidence=["C"], evidence_card=[2]),
        TabularCPD(
            "W", 2,
            [[0.99, 0.10, 0.10, 0.01], [0.01, 0.90, 0.90, 0.99]],
            evidence=["R", "S"], evidence_card=[2, 2],
        ),
    )
    return model
